sudo cp crt1.o /usr/lib/
sudo cp crtbegin.o /usr/lib/
sudo cp crtbeginS.o /usr/lib/
sudo cp crtend.o /usr/lib/
sudo cp crtendS.o /usr/lib/
sudo cp crti.o /usr/lib/
sudo cp crtn.o /usr/lib/
sudo cp libc.so /usr/lib/
sudo cp libc_nonshared.a /usr/lib/x86_64-linux-gnu/
sudo cp libgcc.a /usr/lib/
sudo cp libgcc_s.so /usr/lib/